# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Tugdual LE PELLETER/Documents/Recherche/Repositories/core_uart/sources/ip/ip_mmcm/ip_mmcm.xci
# IP: The module: 'ip_mmcm' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Tugdual LE PELLETER/Documents/Recherche/Repositories/core_uart/sources/ip/ip_mmcm/ip_mmcm_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ip_mmcm'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Tugdual LE PELLETER/Documents/Recherche/Repositories/core_uart/sources/ip/ip_mmcm/ip_mmcm.xdc
# XDC: The top module name and the constraint reference have the same name: 'ip_mmcm'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Tugdual LE PELLETER/Documents/Recherche/Repositories/core_uart/sources/ip/ip_mmcm/ip_mmcm_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ip_mmcm'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/Tugdual LE PELLETER/Documents/Recherche/Repositories/core_uart/sources/ip/ip_mmcm/ip_mmcm.xci
# IP: The module: 'ip_mmcm' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Tugdual LE PELLETER/Documents/Recherche/Repositories/core_uart/sources/ip/ip_mmcm/ip_mmcm_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ip_mmcm'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Tugdual LE PELLETER/Documents/Recherche/Repositories/core_uart/sources/ip/ip_mmcm/ip_mmcm.xdc
# XDC: The top module name and the constraint reference have the same name: 'ip_mmcm'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Tugdual LE PELLETER/Documents/Recherche/Repositories/core_uart/sources/ip/ip_mmcm/ip_mmcm_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ip_mmcm'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
